import Foundation

// Audited against Alfred 5.7.3 systemsettings{13,14,15,26}.json.
// Keep names, URL suffixes, icon paths, and order in sync; see docs/system-settings-audit.md.
enum SystemSettingsReference {
    static func panes(for majorVersion: Int) -> [SystemSettingsPane] {
        switch majorVersion {
        case ...13: macOS13
        case 14: macOS14
        case 15..<26: macOS15
        default: macOS26
        }
    }

    private static let macOS13: [SystemSettingsPane] = [
        .init(name: "About", identifier: "com.apple.SystemProfiler.AboutExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AboutExtension.appex"),
        .init(name: "Accessibility", identifier: "com.apple.Accessibility-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AccessibilitySettingsExtension.appex"),
        .init(name: "AirDrop & Handoff", identifier: "com.apple.AirDrop-Handoff-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AirDropHandoffExtension.appex"),
        .init(name: "Appearance", identifier: "com.apple.Appearance-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Appearance.appex"),
        .init(name: "Apple ID", identifier: "com.apple.systempreferences.AppleIDSettings*AppleIDSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AppleIDSettings.appex"),
        .init(name: "Bluetooth", identifier: "com.apple.BluetoothSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Bluetooth.appex"),
        .init(name: "Control Center", identifier: "com.apple.ControlCenter-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ControlCenterSettings.appex"),
        .init(name: "Date & Time", identifier: "com.apple.Date-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DateAndTime Extension.appex"),
        .init(name: "Desktop & Dock", identifier: "com.apple.Desktop-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DesktopSettings.appex"),
        .init(name: "Profiles", identifier: "com.apple.Profiles-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ProfilesSettingsExt.appex"),
        .init(name: "Displays", identifier: "com.apple.Displays-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DisplaysExt.appex"),
        .init(name: "Family", identifier: "com.apple.Family-Settings.extension*Family", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FamilySettings.appex"),
        .init(name: "Focus", identifier: "com.apple.Focus-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FocusSettingsExtension.appex"),
        .init(name: "General", identifier: "com.apple.systempreferences.GeneralSettings", iconBundlePath: "/System/Applications/System Settings.app/Contents/PlugIns/GeneralSettings.appex"),
        .init(name: "Game Center", identifier: "com.apple.Game-Center-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameCenterMacOSSettingsExtension.appex"),
        .init(name: "Game Controllers", identifier: "com.apple.Game-Controller-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameControllerMacSettings.appex"),
        .init(name: "Internet Accounts", identifier: "com.apple.Internet-Accounts-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/InternetAccountsSettingsExtension.appex"),
        .init(name: "Keyboard", identifier: "com.apple.Keyboard-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/KeyboardSettings.appex"),
        .init(name: "Language & Region", identifier: "com.apple.Localization-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Localization.appex"),
        .init(name: "Lock Screen", identifier: "com.apple.Lock-Screen-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LockScreen.appex"),
        .init(name: "Login Items", identifier: "com.apple.LoginItems-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LoginItems.appex"),
        .init(name: "Mouse", identifier: "com.apple.Mouse-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/MouseExtension.appex"),
        .init(name: "Network", identifier: "com.apple.Network-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Network.appex"),
        .init(name: "Notifications", identifier: "com.apple.Notifications-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/NotificationsSettings.appex"),
        .init(name: "Printers & Scanners", identifier: "com.apple.Print-Scan-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/PrinterScannerSettings.appex"),
        .init(name: "Privacy & Security", identifier: "com.apple.settings.PrivacySecurity.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex"),
        .init(name: "Screen Saver", identifier: "com.apple.ScreenSaver-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Screen Saver.appex"),
        .init(name: "Screen Time", identifier: "com.apple.Screen-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ScreenTimePreferencesExtension.appex"),
        .init(name: "Sharing", identifier: "com.apple.Sharing-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sharing.appex"),
        .init(name: "Software Update", identifier: "com.apple.Software-Update-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SUOSUPreferencePaneExtension.appex"),
        .init(name: "Sound", identifier: "com.apple.Sound-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sound.appex"),
        .init(name: "Startup Disk", identifier: "com.apple.Startup-Disk-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/StartupDisk.appex"),
        .init(name: "Storage", identifier: "com.apple.settings.Storage", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Storage.appex"),
        .init(name: "Time Machine", identifier: "com.apple.Time-Machine-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TimeMachineSettings.appex"),
        .init(name: "Touch ID & Password", identifier: "com.apple.Touch-ID-Settings.extension*TouchIDPasswordPrefs", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Touch ID & Password.appex"),
        .init(name: "Trackpad", identifier: "com.apple.Trackpad-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TrackpadExtension.appex"),
        .init(name: "Transfer or Reset", identifier: "com.apple.Transfer-Reset-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TransferResetExtension.appex"),
        .init(name: "Users & Groups", identifier: "com.apple.Users-Groups-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/UsersGroups.appex"),
        .init(name: "Wallet & Apple Pay", identifier: "com.apple.WalletSettingsExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/WalletSettingsExtension.appex"),
        .init(name: "VPN", identifier: "com.apple.NetworkExtensionSettingsUI.NESettingsUIExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/VPN.appex"),
        .init(name: "Wallpaper", identifier: "com.apple.Wallpaper-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wallpaper.appex"),
        .init(name: "Wi‑Fi", identifier: "com.apple.wifi-settings-extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/WiFiSettings.appex"),
        .init(name: "Battery", identifier: "com.apple.Battery-Settings.extension", iconBundlePath: nil),
        .init(name: "Siri & Spotlight", identifier: "com.apple.Siri-Settings.extension", iconBundlePath: "/System/Applications/Siri.app"),
        .init(name: "iCloud", identifier: "com.apple.systempreferences.AppleIDSettings:icloud", iconBundlePath: "/System/Library/CoreServices/Finder.app/Contents/Applications/iCloud Drive.app"),
        .init(name: "Passwords", identifier: "com.apple.Passwords-Settings.extension", iconBundlePath: "/System/Volumes/Preboot/Cryptexes/App/System/Library/CoreServices/PasswordsSettingsExtension.appex"),
    ]

    private static let macOS14: [SystemSettingsPane] = [
        .init(name: "About", identifier: "com.apple.SystemProfiler.AboutExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AboutExtension.appex"),
        .init(name: "Accessibility", identifier: "com.apple.Accessibility-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AccessibilitySettingsExtension.appex"),
        .init(name: "AirDrop & Handoff", identifier: "com.apple.AirDrop-Handoff-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AirDropHandoffExtension.appex"),
        .init(name: "Appearance", identifier: "com.apple.Appearance-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Appearance.appex"),
        .init(name: "AppleCare & Warranty", identifier: "com.apple.Coverage-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/CoverageSettings.appex"),
        .init(name: "Apple ID", identifier: "com.apple.systempreferences.AppleIDSettings*AppleIDSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AppleIDSettings.appex"),
        .init(name: "Bluetooth", identifier: "com.apple.BluetoothSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Bluetooth.appex"),
        .init(name: "Control Center", identifier: "com.apple.ControlCenter-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ControlCenterSettings.appex"),
        .init(name: "Date & Time", identifier: "com.apple.Date-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DateAndTime Extension.appex"),
        .init(name: "Desktop & Dock", identifier: "com.apple.Desktop-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DesktopSettings.appex"),
        .init(name: "Profiles", identifier: "com.apple.Profiles-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ProfilesSettingsExt.appex"),
        .init(name: "Displays", identifier: "com.apple.Displays-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DisplaysExt.appex"),
        .init(name: "Family", identifier: "com.apple.Family-Settings.extension*Family", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FamilySettings.appex"),
        .init(name: "Focus", identifier: "com.apple.Focus-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FocusSettingsExtension.appex"),
        .init(name: "General", identifier: "com.apple.systempreferences.GeneralSettings", iconBundlePath: "/System/Applications/System Settings.app/Contents/PlugIns/GeneralSettings.appex"),
        .init(name: "Game Center", identifier: "com.apple.Game-Center-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameCenterMacOSSettingsExtension.appex"),
        .init(name: "Game Controllers", identifier: "com.apple.Game-Controller-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameControllerMacSettings.appex"),
        .init(name: "Internet Accounts", identifier: "com.apple.Internet-Accounts-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/InternetAccountsSettingsExtension.appex"),
        .init(name: "Keyboard", identifier: "com.apple.Keyboard-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/KeyboardSettings.appex"),
        .init(name: "Language & Region", identifier: "com.apple.Localization-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Localization.appex"),
        .init(name: "Lock Screen", identifier: "com.apple.Lock-Screen-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LockScreen.appex"),
        .init(name: "Login Items", identifier: "com.apple.LoginItems-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LoginItems.appex"),
        .init(name: "Mouse", identifier: "com.apple.Mouse-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/MouseExtension.appex"),
        .init(name: "Network", identifier: "com.apple.Network-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Network.appex"),
        .init(name: "Notifications", identifier: "com.apple.Notifications-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/NotificationsSettings.appex"),
        .init(name: "Printers & Scanners", identifier: "com.apple.Print-Scan-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/PrinterScannerSettings.appex"),
        .init(name: "Privacy & Security", identifier: "com.apple.settings.PrivacySecurity.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex"),
        .init(name: "Screen Saver", identifier: "com.apple.ScreenSaver-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Screen Saver.appex"),
        .init(name: "Screen Time", identifier: "com.apple.Screen-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ScreenTimePreferencesExtension.appex"),
        .init(name: "Sharing", identifier: "com.apple.Sharing-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sharing.appex"),
        .init(name: "Software Update", identifier: "com.apple.Software-Update-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SoftwareUpdateSettingsExtension.appex"),
        .init(name: "Sound", identifier: "com.apple.Sound-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sound.appex"),
        .init(name: "Startup Disk", identifier: "com.apple.Startup-Disk-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/StartupDisk.appex"),
        .init(name: "Storage", identifier: "com.apple.settings.Storage", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Storage.appex"),
        .init(name: "Time Machine", identifier: "com.apple.Time-Machine-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TimeMachineSettings.appex"),
        .init(name: "Touch ID & Password", identifier: "com.apple.Touch-ID-Settings.extension*TouchIDPasswordPrefs", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Touch ID & Password.appex"),
        .init(name: "Trackpad", identifier: "com.apple.Trackpad-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TrackpadExtension.appex"),
        .init(name: "Transfer or Reset", identifier: "com.apple.Transfer-Reset-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TransferResetExtension.appex"),
        .init(name: "Users & Groups", identifier: "com.apple.Users-Groups-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/UsersGroups.appex"),
        .init(name: "Wallet & Apple Pay", identifier: "com.apple.WalletSettingsExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/WalletSettingsExtension.appex"),
        .init(name: "VPN", identifier: "com.apple.NetworkExtensionSettingsUI.NESettingsUIExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/VPN.appex"),
        .init(name: "Wallpaper", identifier: "com.apple.Wallpaper-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wallpaper.appex"),
        .init(name: "Wi‑Fi", identifier: "com.apple.wifi-settings-extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wi-Fi.appex"),
        .init(name: "Battery", identifier: "com.apple.Battery-Settings.extension*BatteryPreferences", iconBundlePath: nil),
        .init(name: "Siri & Spotlight", identifier: "com.apple.Siri-Settings.extension*siri-sae", iconBundlePath: "/System/Applications/Siri.app"),
        .init(name: "iCloud", identifier: "com.apple.systempreferences.AppleIDSettings:icloud", iconBundlePath: "/System/Library/CoreServices/Finder.app/Contents/Applications/iCloud Drive.app"),
        .init(name: "Passwords", identifier: "com.apple.Passwords-Settings.extension", iconBundlePath: "/System/Volumes/Preboot/Cryptexes/App/System/Library/CoreServices/PasswordsSettingsExtension.appex"),
    ]

    private static let macOS15: [SystemSettingsPane] = [
        .init(name: "About", identifier: "com.apple.SystemProfiler.AboutExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AboutExtension.appex"),
        .init(name: "Accessibility", identifier: "com.apple.Accessibility-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AccessibilitySettingsExtension.appex"),
        .init(name: "AirDrop & Handoff", identifier: "com.apple.AirDrop-Handoff-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AirDropHandoffExtension.appex"),
        .init(name: "Appearance", identifier: "com.apple.Appearance-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Appearance.appex"),
        .init(name: "AppleCare & Warranty", identifier: "com.apple.Coverage-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/CoverageSettings.appex"),
        .init(name: "Apple Account", identifier: "com.apple.systempreferences.AppleIDSettings*AppleIDSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AppleIDSettings.appex"),
        .init(name: "Bluetooth", identifier: "com.apple.BluetoothSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Bluetooth.appex"),
        .init(name: "Control Center", identifier: "com.apple.ControlCenter-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ControlCenterSettings.appex"),
        .init(name: "Date & Time", identifier: "com.apple.Date-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DateAndTime Extension.appex"),
        .init(name: "Desktop & Dock", identifier: "com.apple.Desktop-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DesktopSettings.appex"),
        .init(name: "Device Management", identifier: "com.apple.Profiles-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ProfilesSettingsExt.appex"),
        .init(name: "Displays", identifier: "com.apple.Displays-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DisplaysExt.appex"),
        .init(name: "Family", identifier: "com.apple.Family-Settings.extension*Family", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FamilySettings.appex"),
        .init(name: "Focus", identifier: "com.apple.Focus-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FocusSettingsExtension.appex"),
        .init(name: "General", identifier: "com.apple.systempreferences.GeneralSettings", iconBundlePath: "/System/Applications/System Settings.app/Contents/PlugIns/GeneralSettings.appex"),
        .init(name: "Game Center", identifier: "com.apple.Game-Center-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameCenterMacOSSettingsExtension.appex"),
        .init(name: "Game Controllers", identifier: "com.apple.Game-Controller-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameControllerMacSettings.appex"),
        .init(name: "Internet Accounts", identifier: "com.apple.Internet-Accounts-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/InternetAccountsSettingsExtension.appex"),
        .init(name: "Keyboard", identifier: "com.apple.Keyboard-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/KeyboardSettings.appex"),
        .init(name: "Language & Region", identifier: "com.apple.Localization-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Localization.appex"),
        .init(name: "Lock Screen", identifier: "com.apple.Lock-Screen-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LockScreen.appex"),
        .init(name: "Login Items & Extensions", identifier: "com.apple.LoginItems-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LoginItems.appex"),
        .init(name: "Mouse", identifier: "com.apple.Mouse-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/MouseExtension.appex"),
        .init(name: "Network", identifier: "com.apple.Network-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Network.appex"),
        .init(name: "Notifications", identifier: "com.apple.Notifications-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/NotificationsSettings.appex"),
        .init(name: "Printers & Scanners", identifier: "com.apple.Print-Scan-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/PrinterScannerSettings.appex"),
        .init(name: "Privacy & Security", identifier: "com.apple.settings.PrivacySecurity.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex"),
        .init(name: "Screen Saver", identifier: "com.apple.ScreenSaver-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Screen Saver.appex"),
        .init(name: "Screen Time", identifier: "com.apple.Screen-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ScreenTimePreferencesExtension.appex"),
        .init(name: "Sharing", identifier: "com.apple.Sharing-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sharing.appex"),
        .init(name: "Spotlight", identifier: "com.apple.Spotlight-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SpotlightPreferenceExtension.appex"),
        .init(name: "Software Update", identifier: "com.apple.Software-Update-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SoftwareUpdateSettingsExtension.appex"),
        .init(name: "Sound", identifier: "com.apple.Sound-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sound.appex"),
        .init(name: "Startup Disk", identifier: "com.apple.Startup-Disk-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/StartupDisk.appex"),
        .init(name: "Storage", identifier: "com.apple.settings.Storage", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Storage.appex"),
        .init(name: "Time Machine", identifier: "com.apple.Time-Machine-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TimeMachineSettings.appex"),
        .init(name: "Touch ID & Password", identifier: "com.apple.Touch-ID-Settings.extension*TouchIDPasswordPrefs", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Touch ID & Password.appex"),
        .init(name: "Trackpad", identifier: "com.apple.Trackpad-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TrackpadExtension.appex"),
        .init(name: "Transfer or Reset", identifier: "com.apple.Transfer-Reset-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TransferResetExtension.appex"),
        .init(name: "Users & Groups", identifier: "com.apple.Users-Groups-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/UsersGroups.appex"),
        .init(name: "Wallet & Apple Pay", identifier: "com.apple.WalletSettingsExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/WalletSettingsExtension.appex"),
        .init(name: "VPN", identifier: "com.apple.NetworkExtensionSettingsUI.NESettingsUIExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/VPN.appex"),
        .init(name: "Wallpaper", identifier: "com.apple.Wallpaper-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wallpaper.appex"),
        .init(name: "Wi‑Fi", identifier: "com.apple.wifi-settings-extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wi-Fi.appex"),
        .init(name: "Battery", identifier: "com.apple.Battery-Settings.extension*BatteryPreferences", iconBundlePath: nil),
        .init(name: "Apple Intelligence & Siri", identifier: "com.apple.Siri-Settings.extension*siri-sae", iconBundlePath: "/System/Applications/Siri.app"),
        .init(name: "iCloud", identifier: "com.apple.systempreferences.AppleIDSettings:icloud", iconBundlePath: "/System/Library/CoreServices/Finder.app/Contents/Applications/iCloud Drive.app"),
    ]

    private static let macOS26: [SystemSettingsPane] = [
        .init(name: "About", identifier: "com.apple.SystemProfiler.AboutExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AboutExtension.appex"),
        .init(name: "Accessibility", identifier: "com.apple.Accessibility-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AccessibilitySettingsExtension.appex"),
        .init(name: "AirDrop & Handoff", identifier: "com.apple.AirDrop-Handoff-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AirDropHandoffExtension.appex"),
        .init(name: "Appearance", identifier: "com.apple.Appearance-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Appearance.appex"),
        .init(name: "AppleCare & Warranty", identifier: "com.apple.Coverage-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/CoverageSettings.appex"),
        .init(name: "Apple Account", identifier: "com.apple.systempreferences.AppleIDSettings*AppleIDSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/AppleIDSettings.appex"),
        .init(name: "Bluetooth", identifier: "com.apple.BluetoothSettings", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Bluetooth.appex"),
        .init(name: "Date & Time", identifier: "com.apple.Date-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DateAndTime Extension.appex"),
        .init(name: "Desktop & Dock", identifier: "com.apple.Desktop-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DesktopSettings.appex"),
        .init(name: "Device Management", identifier: "com.apple.Profiles-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ProfilesSettingsExt.appex"),
        .init(name: "Displays", identifier: "com.apple.Displays-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/DisplaysExt.appex"),
        .init(name: "Family", identifier: "com.apple.Family-Settings.extension*Family", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FamilySettings.appex"),
        .init(name: "Focus", identifier: "com.apple.Focus-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/FocusSettingsExtension.appex"),
        .init(name: "General", identifier: "com.apple.systempreferences.GeneralSettings", iconBundlePath: "/System/Applications/System Settings.app/Contents/PlugIns/GeneralSettings.appex"),
        .init(name: "Game Center", identifier: "com.apple.Game-Center-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameCenterMacOSSettingsExtension.appex"),
        .init(name: "Game Controllers", identifier: "com.apple.Game-Controller-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/GameControllerMacSettings.appex"),
        .init(name: "Internet Accounts", identifier: "com.apple.Internet-Accounts-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/InternetAccountsSettingsExtension.appex"),
        .init(name: "Keyboard", identifier: "com.apple.Keyboard-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/KeyboardSettings.appex"),
        .init(name: "Language & Region", identifier: "com.apple.Localization-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Localization.appex"),
        .init(name: "Lock Screen", identifier: "com.apple.Lock-Screen-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LockScreen.appex"),
        .init(name: "Login Items & Extensions", identifier: "com.apple.LoginItems-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/LoginItems.appex"),
        .init(name: "Mouse", identifier: "com.apple.Mouse-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/MouseExtension.appex"),
        .init(name: "Network", identifier: "com.apple.Network-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Network.appex"),
        .init(name: "Notifications", identifier: "com.apple.Notifications-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/NotificationsSettings.appex"),
        .init(name: "Printers & Scanners", identifier: "com.apple.Print-Scan-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/PrinterScannerSettings.appex"),
        .init(name: "Privacy & Security", identifier: "com.apple.settings.PrivacySecurity.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SecurityPrivacyExtension.appex"),
        .init(name: "Screen Time", identifier: "com.apple.Screen-Time-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/ScreenTimePreferencesExtension.appex"),
        .init(name: "Sharing", identifier: "com.apple.Sharing-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sharing.appex"),
        .init(name: "Spotlight", identifier: "com.apple.Spotlight-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SpotlightPreferenceExtension.appex"),
        .init(name: "Software Update", identifier: "com.apple.Software-Update-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/SoftwareUpdateSettingsExtension.appex"),
        .init(name: "Sound", identifier: "com.apple.Sound-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Sound.appex"),
        .init(name: "Startup Disk", identifier: "com.apple.Startup-Disk-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/StartupDisk.appex"),
        .init(name: "Storage", identifier: "com.apple.settings.Storage", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Storage.appex"),
        .init(name: "Time Machine", identifier: "com.apple.Time-Machine-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TimeMachineSettings.appex"),
        .init(name: "Touch ID & Password", identifier: "com.apple.Touch-ID-Settings.extension*TouchIDPasswordPrefs", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Touch ID & Password.appex"),
        .init(name: "Trackpad", identifier: "com.apple.Trackpad-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TrackpadExtension.appex"),
        .init(name: "Transfer or Reset", identifier: "com.apple.Transfer-Reset-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/TransferResetExtension.appex"),
        .init(name: "Users & Groups", identifier: "com.apple.Users-Groups-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/UsersGroups.appex"),
        .init(name: "Wallet & Apple Pay", identifier: "com.apple.WalletSettingsExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/WalletSettingsExtension.appex"),
        .init(name: "VPN", identifier: "com.apple.NetworkExtensionSettingsUI.NESettingsUIExtension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/VPN.appex"),
        .init(name: "Wallpaper", identifier: "com.apple.Wallpaper-Settings.extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wallpaper.appex"),
        .init(name: "Wi‑Fi", identifier: "com.apple.wifi-settings-extension", iconBundlePath: "/System/Library/ExtensionKit/Extensions/Wi-Fi.appex"),
        .init(name: "Battery", identifier: "com.apple.Battery-Settings.extension*BatteryPreferences", iconBundlePath: nil),
        .init(name: "Menu Bar", identifier: "com.apple.ControlCenter-Settings.extension*menubar", iconBundlePath: nil),
        .init(name: "Apple Intelligence & Siri", identifier: "com.apple.Siri-Settings.extension*siri-sae", iconBundlePath: "/System/Applications/Siri.app"),
        .init(name: "iCloud", identifier: "com.apple.systempreferences.AppleIDSettings:icloud", iconBundlePath: "/System/Library/CoreServices/Finder.app/Contents/Applications/iCloud Drive.app"),
    ]
}
